spring:
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

logging:
  level:
    com:
      varc:
        brewnetapp: INFO